import React from 'react';
import { FileText, Scale, Zap, AlertTriangle, ArrowLeft } from 'lucide-react';

export const TermsOfService: React.FC<{ onClose: () => void }> = ({ onClose }) => {
    return (
        <div className="fixed inset-0 z-[100] bg-white overflow-y-auto animate-in fade-in duration-300">
            <div className="max-w-4xl mx-auto px-6 py-12">
                <button
                    onClick={onClose}
                    className="mb-8 flex items-center gap-2 text-slate-500 hover:text-slate-900 transition-colors group"
                >
                    <ArrowLeft className="w-5 h-5 group-hover:-translate-x-1 transition-transform" />
                    Back to Library
                </button>

                <header className="mb-12">
                    <div className="bg-purple-100 w-16 h-16 rounded-2xl flex items-center justify-center text-purple-600 mb-6">
                        <Scale className="w-8 h-8" />
                    </div>
                    <h1 className="text-4xl font-extrabold text-slate-900 mb-4">Terms of Service</h1>
                    <p className="text-slate-500">Last updated: February 2, 2026</p>
                </header>

                <div className="prose prose-slate max-w-none space-y-8 text-slate-700">
                    <section>
                        <h2 className="text-2xl font-bold text-slate-900 mb-4 flex items-center gap-2">
                            <Zap className="w-5 h-5 text-purple-500" /> 1. Acceptance of Terms
                        </h2>
                        <p>By accessing or using Myers Prompt Guru, you agree to be bound by these Terms of Service. If you do not agree to all of these terms, do not use our services.</p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-slate-900 mb-4 flex items-center gap-2">
                            <Zap className="w-5 h-5 text-purple-500" /> 2. Pro Subscriptions
                        </h2>
                        <p>Our Pro features (AI Guru, Bulk Import, OCR) are provided on a monthly subscription basis. Subscriptions are billed in advance and are non-refundable except as required by law. You may cancel your subscription at any time via your Stripe portal.</p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-slate-900 mb-4 flex items-center gap-2">
                            <FileText className="w-5 h-5 text-purple-500" /> 3. Intellectual Property
                        </h2>
                        <p>You retain ownership of any prompts you create or import. However, you grant Myers Digital Services a worldwide, non-exclusive license to host, store, and display your content solely for the purpose of providing the service to you.</p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-slate-900 mb-4 flex items-center gap-2">
                            <AlertTriangle className="w-5 h-5 text-purple-500" /> 4. Disclaimer of AI Output
                        </h2>
                        <p>AI-generated content and Guru advice are provided "as-is" for informational purposes. We do not guarantee the accuracy, safety, or effectiveness of prompts or advice generated by our AI services. Users are responsible for testing and validating any prompt before production use.</p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-slate-900 mb-4 flex items-center gap-2">
                            <Scale className="w-5 h-5 text-purple-500" /> 5. Limitation of Liability
                        </h2>
                        <p>Myers Digital Services shall not be liable for any indirect, incidental, special, or consequential damages resulting from the use or inability to use our services.</p>
                    </section>

                    <footer className="pt-12 border-t border-slate-100 text-sm text-slate-400">
                        <p>&copy; 2026 Myers Digital Services. All rights reserved.</p>
                    </footer>
                </div>
            </div>
        </div>
    );
};
